// LOCALHOST:3000

### GET ALL CONTACTS
GET http://localhost:3000/contacts

### GET CONTACT BY ID
GET http://localhost:3000/contacts/59b99db4cfa9a34dcd7885b6

### CREATE CONTACT
POST http://localhost:3000/contacts
Content-Type: application/json

  {
     "firstName": "Jon",
      "lastName": " Snow",
    "email": "kit_harington@gameofthron.es",
    "favoriteColor": "red",
    "birthday": "01/01/1990"
  }

### UPDATE CONTACT
PUT http://localhost:3000/contacts/682dc8a20e0d5ddd62252bdf
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "jane@email.com",
  "favoriteColor": "red",
  "birthday": "02/02/1992"
}

### DELETE CONTACT
DELETE http://localhost:3000/contacts/682dc82c0e0d5ddd62252bd9
